# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v1.0.0

# - source: test/base_test.pine

from typing import List as array 
from typing import Dict as map 

def foo() :
y = 5
foo = "foo"
if foo > 5:
    foo = 4
    foo = 1
    while y == 5:
        v = 5 + 1
        v = 5
return f
