# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v0.0.1

# - source: test/base_test.pine

# indicator
print("my indicator sksodd")
# strategy
print(" ofofof")
xss_aa = "appa"
# indicator
print("REAL")
# strategy
print("FOO")
# strategy
print("DLDLDL")
