# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v1.0.0

# - source: test/base_test.pine

from typing import List as array 
from typing import Dict as map 

# a constant variable!
MAX_COUNT = 100
# a constant variable!
THRESHOLD = 50
# a constant variable!
FOL = 30
def complex_func(arr: array[int], map_name: array.ta[str.ta], flag: bool, name: str):
    return     if result > 5:
result + 2