const foo = "rma"
const xss = 5

foo = 5
if foo
   y = 5

if xss != 5
   indicator("the error of xss occured!")

switch f
    =>    indicator("no")

foo = f
switch foo
   fooa => indicator("soo")
   "RMA" => strategy("ll")
   "WMA" => indicator("it's a fooo")
   => indicator("cant process")

switch foo
   foo => indicator("sorry")
   "FOO" => strategy("real")
   => indicator("gonna out!")




foo = 1
