# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v0.0.1

# - source: test/foo.pine

from typing import List as array 
from typing import Dict as map 
import csv
import os


csv_path = input("Enter the path to your OHLC CSV file: ").strip()

csv_path = csv_path.strip('"').strip("'")

if not os.path.exists(csv_path):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    alt_path = os.path.join(script_dir, os.path.basename(csv_path))
    if os.path.exists(alt_path):
        csv_path = alt_path
    else:
        raise FileNotFoundError(f"File not found: {csv_path}")

open = []
high = []
low = []
close = []
volume = []
time = []

with open(csv_path, 'r') as f:
    reader = csv.reader(f)
    header = next(reader, None)
    for row in reader:
        if len(row) >= 5:
            time.append(row[0])
            open.append(float(row[1]))
            high.append(float(row[2]))
            low.append(float(row[3]))
            close.append(float(row[4]))
            volume.append(float(row[5]) if len(row) > 5 else 0.0)

print(f"Loaded {len(close)} bars from {csv_path}\n")


for bar in close:
    0x561b79081f40("ICT Liquidity Void Multi-timeframe")
    g_lv = "███████████████ Liquidity Void ███████████████"
    str    i_lv_htf =     0x561b79082520("")

    int    i_lv_show_last =     0x561b790829c0(2)

    str    i_lv_line =     0x561b79092360("High/Low")

    bool    i_lv_bear_show =     0x561b790929e0(    true
)

    bool    i_lv_bull_show =     0x561b79092e80(    true
)

    bool    i_lv_hide_crossed =     0x561b79093320(    false
)

    g_lv_f = "Void Height Filter"
