# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v0.0.1

# - source: test/ICD_EXTERNAL_RANGE.pine

from typing import List as array 
from typing import Dict as map 
import csv
import os


csv_path = input("Enter the path to your OHLC CSV file: ").strip()

csv_path = csv_path.strip('"').strip("'")

if not os.path.exists(csv_path):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    alt_path = os.path.join(script_dir, os.path.basename(csv_path))
    if os.path.exists(alt_path):
        csv_path = alt_path
    else:
        raise FileNotFoundError(f"File not found: {csv_path}")

open = []
high = []
low = []
close = []
volume = []
time = []

with open(csv_path, 'r') as f:
    reader = csv.reader(f)
    header = next(reader, None)
    for row in reader:
        if len(row) >= 5:
            time.append(row[0])
            open.append(float(row[1]))
            high.append(float(row[2]))
            low.append(float(row[3]))
            close.append(float(row[4]))
            volume.append(float(row[5]) if len(row) > 5 else 0.0)

print(f"Loaded {len(close)} bars from {csv_path}\n")
i_max_bars_back = 4999
0x5617ad184a20("ICT External Range Liquidity Static Multi-timeframe @Swing High and Low@")
g_phl_qd = "███████████████ Quick On/Off ███████████████"
booli_phl_1_show = 0x5617ad18de10(true
)

booli_phl_2_show = 0x5617ad18e2b0(true
)

booli_phl_3_show = 0x5617ad18e750(true
)

booli_phl_eq_show = 0x5617ad18ebf0(true
)

g_phl_co = "██████████████ Common Settings ██████████████"
stri_phl_1_source = 0x5617ad18f170("High/Low")

g_phl_1 = "██████████████ Pivot High Low 1 ██████████████"
stri_phl_1_tf = 0x5617ad18f890("15")

inti_phl_1_left = 0x5617ad18fd30(2)

inti_phl_1_right = 0x5617ad1901b0(2)

inti_phl_1_showlast = 0x5617ad190630(2)

booli_phl_1_ln_extend = 0x5617ad193cf0(false
)

colori_phl_1_h_ln_color = 0x5617ad194190(0)

colori_phl_1_l_ln_color = 0x5617ad194610(0)

stri_phl_1_ln_stye = 0x5617ad194a90(line.style_solid
)

inti_phl_1_ln_width = 0x5617ad195130(2)

booli_phl_1_lbl_show = 0x5617ad195690(false
)

g_phl_2 = "██████████████ Pivot High Low 2 ██████████████"
stri_phl_2_tf = 0x5617ad195c80("60")

inti_phl_2_left = 0x5617ad196120(2)

inti_phl_2_right = 0x5617ad1965a0(2)

inti_phl_2_showlast = 0x5617ad196a20(2)

booli_phl_2_ln_extend = 0x5617ad196f80(false
)

colori_phl_2_h_ln_color = 0x5617ad197420(0)

colori_phl_2_l_ln_color = 0x5617ad1a4050(0)

stri_phl_2_ln_stye = 0x5617ad1a44d0(line.style_solid
)

inti_phl_2_ln_width = 0x5617ad1a4b70(2)

booli_phl_2_lbl_show = 0x5617ad1a50d0(false
)

g_phl_3 = "██████████████ Pivot High Low 3 ██████████████"
stri_phl_3_tf = 0x5617ad1a56c0("240")

inti_phl_3_left = 0x5617ad1a5b60(2)

inti_phl_3_right = 0x5617ad1a5fe0(2)

inti_phl_3_showlast = 0x5617ad1a6460(2)

booli_phl_3_ln_extend = 0x5617ad1a69c0(false
)

colori_phl_3_h_ln_color = 0x5617ad1a6e60(0)

colori_phl_3_l_ln_color = 0x5617ad1a72e0(0)

stri_phl_3_ln_stye = 0x5617ad1a7760(line.style_solid
)

inti_phl_3_ln_width = 0x5617ad1a7e00(2)

booli_phl_3_lbl_show = 0x5617ad1a8360(false
)

g_phl_eq = "███████████████ Equal High Low ███████████████"
inti_phl_eq_left = 0x5617ad1a8960(60)

inti_phl_eq_right = 0x5617ad1a8de0(30)

tt_eq = "Lower values mean highs and lows are closer."
floati_phl_eq_percent = 0x5617ad1a9380(-1390767328)

colori_phl_eq_h_ln_color = 0x5617ad1a9b00(0)

colori_phl_eq_l_ln_color = 0x5617ad1a9f80(0)

inti_phl_eq_transp = 0x5617ad1aa400(25)

def f_offsetToP(_src, _pivotPrice, _maxBack):
    int    _offset = na
    float    _delta = 10
    e10    if !0x5617ad1aade0(_pivotPrice)
:
        for _i in range(1, _maxBack + 1):
1
    return     _offsetdef f_resInMinutes():
    _resInMinutes = timeframe.multiplier * ( 1 / 60 if timeframe.isseconds else 1 if timeframe.isminutes else 1440 if timeframe.isdaily else 10080 if timeframe.isweekly else 43800 if timeframe.ismonthly else na




 )

    return     _resInMinutesdef f_tfResInMinutes(_resolution):

    return     0x5617ad1ac440(syminfo.tickerid
)
