# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v0.0.1

# - source: test/ICD_EXTERNAL_RANGE.pine

from typing import List as array 
from typing import Dict as map 
import csv
import os


csv_path = input("Enter the path to your OHLC CSV file: ").strip()

csv_path = csv_path.strip('"').strip("'")

if not os.path.exists(csv_path):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    alt_path = os.path.join(script_dir, os.path.basename(csv_path))
    if os.path.exists(alt_path):
        csv_path = alt_path
    else:
        raise FileNotFoundError(f"File not found: {csv_path}")

open = []
high = []
low = []
close = []
volume = []
time = []

with open(csv_path, 'r') as f:
    reader = csv.reader(f)
    header = next(reader, None)
    for row in reader:
        if len(row) >= 5:
            time.append(row[0])
            open.append(float(row[1]))
            high.append(float(row[2]))
            low.append(float(row[3]))
            close.append(float(row[4]))
            volume.append(float(row[5]) if len(row) > 5 else 0.0)

print(f"Loaded {len(close)} bars from {csv_path}\n")
i_max_bars_back = 4999
0x564d6f55c660("ICT External Range Liquidity Static Multi-timeframe @Swing High and Low@")
g_phl_qd = "███████████████ Quick On/Off ███████████████"
booli_phl_1_show = 0x564d6f56c680(true
)

booli_phl_2_show = 0x564d6f56cb20(true
)

booli_phl_3_show = 0x564d6f56cfc0(true
)

booli_phl_eq_show = 0x564d6f56d460(true
)

g_phl_co = "██████████████ Common Settings ██████████████"
stri_phl_1_source = 0x564d6f56d9e0("High/Low")

g_phl_1 = "██████████████ Pivot High Low 1 ██████████████"
stri_phl_1_tf = 0x564d6f56e100("15")

inti_phl_1_left = 0x564d6f57b280(2)

inti_phl_1_right = 0x564d6f57b700(2)

inti_phl_1_showlast = 0x564d6f57bb80(2)

booli_phl_1_ln_extend = 0x564d6f57c0e0(false
)

colori_phl_1_h_ln_color = 0x564d6f57c580(0)

colori_phl_1_l_ln_color = 0x564d6f57ca00(0)

stri_phl_1_ln_stye = 0x564d6f57ce80(line.style_solid
)

inti_phl_1_ln_width = 0x564d6f57d520(2)

booli_phl_1_lbl_show = 0x564d6f57da80(false
)

g_phl_2 = "██████████████ Pivot High Low 2 ██████████████"
stri_phl_2_tf = 0x564d6f57e070("60")

inti_phl_2_left = 0x564d6f57e510(2)

inti_phl_2_right = 0x564d6f57e990(2)

inti_phl_2_showlast = 0x564d6f57ee10(2)

booli_phl_2_ln_extend = 0x564d6f57f370(false
)

colori_phl_2_h_ln_color = 0x564d6f57f810(0)

colori_phl_2_l_ln_color = 0x564d6f57fc90(0)

stri_phl_2_ln_stye = 0x564d6f580110(line.style_solid
)

inti_phl_2_ln_width = 0x564d6f5807b0(2)

booli_phl_2_lbl_show = 0x564d6f580d10(false
)

g_phl_3 = "██████████████ Pivot High Low 3 ██████████████"
stri_phl_3_tf = 0x564d6f581300("240")

inti_phl_3_left = 0x564d6f5817a0(2)

inti_phl_3_right = 0x564d6f581c20(2)

inti_phl_3_showlast = 0x564d6f5820a0(2)

booli_phl_3_ln_extend = 0x564d6f582600(false
)

colori_phl_3_h_ln_color = 0x564d6f582aa0(0)

colori_phl_3_l_ln_color = 0x564d6f582f20(0)

stri_phl_3_ln_stye = 0x564d6f5833a0(line.style_solid
)

inti_phl_3_ln_width = 0x564d6f583a40(2)

booli_phl_3_lbl_show = 0x564d6f583fa0(false
)

g_phl_eq = "███████████████ Equal High Low ███████████████"
inti_phl_eq_left = 0x564d6f5845a0(60)

inti_phl_eq_right = 0x564d6f584a20(30)

tt_eq = "Lower values mean highs and lows are closer."
floati_phl_eq_percent = 0x564d6f584fc0(1868058464)

colori_phl_eq_h_ln_color = 0x564d6f585740(0)

colori_phl_eq_l_ln_color = 0x564d6f585bc0(0)

inti_phl_eq_transp = 0x564d6f586040(25)

def f_offsetToP(_src, _pivotPrice, _maxBack):
    int    _offset = na
    float    _delta = 10
    e10    if !0x564d6f586a20(_pivotPrice)
:
        for _i in range(1, _maxBack + 1):
1
    return     _offsetdef f_resInMinutes():
    _resInMinutes = timeframe.multiplier * ( 1 / 60 if timeframe.isseconds else 1 if timeframe.isminutes else 1440 if timeframe.isdaily else 10080 if timeframe.isweekly else 43800 if timeframe.ismonthly else na




 )

    return     _resInMinutesdef f_tfResInMinutes(_resolution):

    return     0x564d6f588080(syminfo.tickerid
)
