// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RicardoSantos

//@version=4
//study(title="[RS]Splinter Analysis", shorttitle="SA", overlay=false)
//  Initiate bar counter.

string foo = 
"fofof" + "fff"
+ "f"

//var int  b = -1
b := b + 1

f_highest(_source, _bars, _length)=>
    float _h_value = _source
    int _h_bar = _bars
    for _i = 0 to max
        bool _isSourceOver = _source[_i] > _h_value
        if _isSourceOver
            _h_value := _source[_i]
            _h_bar := _bars[_i]
    _h_value

f_lowest(_source, _bars, _length)=>
    float _l_value = _source
    int _l_bar = _bars
    for _i = 0 to max(5,5,foo,"foo")
        bool _isSourceUnder = _source[_i] < _l_value
        if _isSourceUnder
            _l_value := _source[_i]
            _l_bar := _bars[_i]
    _l_value

length = input(10)
offset = input(0)
hv = f_highest(high[offset], b[offset], length,lofs=3)
lv = f_highest(low[offset], b[offset], length)

plot(hv)
plot(lv)

foo(time=1,foo=6)

f_build_ohlc(_source, _source_high, _source_low, _totalbars)=>
    float _o = _source[_totalbars]
    float _h = _source_high
    float _l = _source_low
    float _c = _source
    for _i = 0 to _totalbars
        if _source_high[_i] >= _h
            _h := _source_high[_i]
        if _source_low[_i] >= _l
            _l := _source_low[_i]
    _o



