# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v0.0.1

# - source: test/yet_test.pine

from typing import List as array 
from typing import Dict as map 
import csv
import os


csv_path = input("Enter the path to your OHLC CSV file: ").strip()

csv_path = csv_path.strip('"').strip("'")

if not os.path.exists(csv_path):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    alt_path = os.path.join(script_dir, os.path.basename(csv_path))
    if os.path.exists(alt_path):
        csv_path = alt_path
    else:
        raise FileNotFoundError(f"File not found: {csv_path}")

open = []
high = []
low = []
close = []
volume = []
time = []

with open(csv_path, 'r') as f:
    reader = csv.reader(f)
    header = next(reader, None)
    for row in reader:
        if len(row) >= 5:
            time.append(row[0])
            open.append(float(row[1]))
            high.append(float(row[2]))
            low.append(float(row[3]))
            close.append(float(row[4]))
            volume.append(float(row[5]) if len(row) > 5 else 0.0)

print(f"Loaded {len(close)} bars from {csv_path}\n")


for bar in close:
# a constant variable!
    FOO = 5
    str    i_phl_1_source =     0x55e543f4e100("High/Low")

    i_max_bars_back = 300
    0x55e543f54dd0("ICT Equal Highs and Lows")
    g_phl_eq = "███████████████ Equal High Low ███████████████"
    int    i_phl_1_left =     0x55e543f4d090(60)

    int    i_phl_1_right =     0x55e543f50cf0(30)

    tt_eq = "Lower values mean highs and lows are closer."
    float    i_phl_eq_percent =     0x55e543f51290(0.05)

    str    i_phl_1_source =     0x55e543f59b10("High/Low")

    color    i_phl_1_h_ln_color =     0x55e543f5a150(0)

    color    i_phl_1_l_ln_color =     0x55e543f5a5d0(0)

    int    i_phl_eq_transp =     0x55e543f5aa50(25)

    pl_bi_arr =     0x55e543f5b1f0(2)

    int    int    prev_pl_bi =     na
    bool    bool    pl =     false
    if !    0x55e543f5b850(    phl_1_ph)
 && 1 == 1:
        ph =     true
        prev_ph_bi =     bar_index -     i_phl_1_right
    0x55e543f5be90(    i_phl_1_right
)
