# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v0.0.1

# - source: test/yet_test.pine

from typing import List as array 
from typing import Dict as map 
import csv
import os


csv_path = input("Enter the path to your OHLC CSV file: ").strip()

csv_path = csv_path.strip('"').strip("'")

if not os.path.exists(csv_path):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    alt_path = os.path.join(script_dir, os.path.basename(csv_path))
    if os.path.exists(alt_path):
        csv_path = alt_path
    else:
        raise FileNotFoundError(f"File not found: {csv_path}")

open = []
high = []
low = []
close = []
volume = []
time = []

with open(csv_path, 'r') as f:
    reader = csv.reader(f)
    header = next(reader, None)
    for row in reader:
        if len(row) >= 5:
            time.append(row[0])
            open.append(float(row[1]))
            high.append(float(row[2]))
            low.append(float(row[3]))
            close.append(float(row[4]))
            volume.append(float(row[5]) if len(row) > 5 else 0.0)

print(f"Loaded {len(close)} bars from {csv_path}\n")
foo = "fofof" + "fff" + "f"
b = b + 1
def f_highest(_source, _bars, _length):
    _h_value = _source
    _h_bar = _bars
    for _i in range(0, max + 1):
        _isSourceOver = _source[_i] > _h_value
        if _isSourceOver:
            _h_value = _source[_i]
            _h_bar = _bars[_i]

    return     _h_valuedef f_lowest(_source, _bars, _length):
    _l_value = _source
    _l_bar = _bars
    for _i in range(0, 0x562545331500(5)
 + 1):
        _isSourceUnder = _source[_i] < _l_value
        if _isSourceUnder:
            _l_value = _source[_i]
            _l_bar = _bars[_i]

    return     _l_valuelength = 0x562545332080(10)

offset = 0x56254532e0c0(0)

hv = 0x56254532e200(offset
)

lv = 0x56254532e580(offset
)

0x56254532e800(hv)
0x56254532e8c0(lv)
0x56254532e980(1)
def f_build_ohlc(_source, _source_high, _source_low, _totalbars):
    _o = _source[_totalbars]
    _h = _source_high
    _l = _source_low
    _c = _source
    for _i in range(0, _totalbars + 1):
        if _source_high[_i] >= _h:
            _h = _source_high[_i]
        if _source_low[_i] >= _l:
            _l = _source_low[_i]

    return     _o