# code generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECESSARY
# - PineFan's version: v0.0.1

# - source: test/yet_test.pine

from typing import List as array 
from typing import Dict as map 
import csv
import os


csv_path = input("Enter the path to your OHLC CSV file: ").strip()

csv_path = csv_path.strip('"').strip("'")

if not os.path.exists(csv_path):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    alt_path = os.path.join(script_dir, os.path.basename(csv_path))
    if os.path.exists(alt_path):
        csv_path = alt_path
    else:
        raise FileNotFoundError(f"File not found: {csv_path}")

open = []
high = []
low = []
close = []
volume = []
time = []

with open(csv_path, 'r') as f:
    reader = csv.reader(f)
    header = next(reader, None)
    for row in reader:
        if len(row) >= 5:
            time.append(row[0])
            open.append(float(row[1]))
            high.append(float(row[2]))
            low.append(float(row[3]))
            close.append(float(row[4]))
            volume.append(float(row[5]) if len(row) > 5 else 0.0)

print(f"Loaded {len(close)} bars from {csv_path}\n")
if !5:
    ff0stri_phl_1_source = 0x5559e52349b0("High/Low")

i_max_bars_back = 300
0x5559e523bd90("ICT Equal Highs and Lows")
g_phl_eq = "███████████████ Equal High Low ███████████████"
inti_phl_1_left = 0x5559e5241ab0(60)

inti_phl_1_right = 0x5559e5241f30(30)

tt_eq = "Lower values mean highs and lows are closer."
floati_phl_eq_percent = 0x5559e52424d0(-450616208)

stri_phl_1_source = 0x5559e5242c50("High/Low")

colori_phl_1_h_ln_color = 0x5559e5243290(0)

colori_phl_1_l_ln_color = 0x5559e5243710(0)

inti_phl_eq_transp = 0x5559e5243b90(25)

float0x5559e5244250(open
)
 if _high = i_phl_1_source == "Open/Close"
 else high
float0x5559e5244670(open
)
 if _low = i_phl_1_source == "Open/Close"
 else low
# a constant variable!
