// TODO:
//  - make  correct adding of output files
//  - do some with if-statemnts to process it correct
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

extern "C" {
#include "ast.h"
#include "parser_rules.tab.h"
#include "vector.h"
//here is the C Vector
}

#include "file.hpp"

#include "ppp.hpp"

#define PINEFAN_VERSION "v0.0.1\n"

int line = 1;
int col = 0;

std::vector<struct ast_node*> program_cpp_root;
 Vector* program_root;

void convert_program_root() {
  if (!program_root) return;

  program_cpp_root.clear();
  program_cpp_root.reserve(program_root->len);

  for (int i = 0; i < program_root->len; i++) {
    ast_node* node = static_cast<ast_node*>(program_root->body[i]);
    program_cpp_root.push_back(node);
  }
}

extern int yylex(void);
extern FILE* yyin;
int line_count = 0;
extern int open_in_count;

std::vector<std::string> source_lines;

void read_source_file(const std::filesystem::path& filename) {
  std::ifstream file(filename);
  if (!file.is_open()) return;

  std::string line;
  while (std::getline(file, line)) {
    source_lines.push_back(line);
  }
}

extern "C" {
void yyerror(const char* s) {
  const std::string_view& message(s);

  auto* file = Pinefan::File::preprocessed_files.back();

  std::cerr << std::format(
      "\e[91m[ERROR]\e[0m: {} \e[92mline\e[0m {} \e[94mcolumn\e[0m {}: {}\n",
      file->get_name(), line, col, message);

  if (source_lines.empty() ||
      static_cast<size_t>(line - 1) >= source_lines.size()) {
    return;
  }

  std::string_view src = source_lines[line - 1];
  if (src.ends_with('\n')) {
    src.remove_suffix(1);
  }

  std::cerr << src << '\n';

  if (col > 0) {
    std::cerr << std::string(col - 1, '~') << "\e[1;32m^\e[0m";

    if (static_cast<size_t>(col) <= src.length()) {
      std::cerr << std::string(src.length() - col, '~');
    }
    std::cerr << '\n';
  }
}
}

void prologue(std::ofstream& output, const std::filesystem::path& source_name) {
  output << "# code generated by the PineFan technology. DO NOT EDIT WITHOUT "
            "OF NECESSARY\n"
         << std::format("# - PineFan's version: {}\n", PINEFAN_VERSION)
         << std::format("# - source: {}\n\n", source_name.string());
}

void indicator(std::string_view str, std::ofstream& output) {
  output << std::format("# indicator\nprint(\"{}\")\n", str);
}
void strategy(std::string_view str, std::ofstream& output) {
  output << std::format("# strategy\nprint(\"{}\")\n", str);
}

void common_var(std::string_view name, ast_node* value, std::ofstream& output) {
  if (!value) return;

  switch (value->type) {
    case AST_NUMBER:
      output << std::format("{} = {}\n", name, value->number.value);
      break;

    case AST_STRING:
      output << std::format("{} = \"{}\"\n", name, value->string.value);
      break;

    default:
      //throw "unknown var";
      break;
  }
}

extern "C" {
void yy_scan_string(const char* str);
void yy_delete_buffer(int);
}

int main(int argc, char* argv[]) {
  Pinefan::Ppp::preprocess_files(argc, argv);

  for (int i = 0; i < Pinefan::File::preprocessed_files.size(); i++) {
    Pinefan::File::Prp_file* prped_file =
        Pinefan::File::preprocessed_files.at(i);

    yy_scan_string(prped_file->get_content().c_str());

    read_source_file(prped_file->get_name());

    std::string pure_name(prped_file->get_name().begin(),
                          prped_file->get_name().end() - 5);

    std::ofstream output_file(pure_name +
                              Pinefan::File::output_exstension.data());

    int r = yyparse();

    if (r) exit(1);

    convert_program_root();

    prologue(output_file, prped_file->get_name());

    for (int j = 0; j < program_cpp_root.size(); j++) {
      auto* val = program_cpp_root.at(j);

      switch (val->type) {
        case AST_INDICATOR: {
          indicator(val->string.value, output_file);
          break;
        }
        case AST_STRATEGY: {
          strategy(val->string.value, output_file);
          break;
        }
        case AST_ASSIGN: {
          common_var(val->assign.name, val->assign.value, output_file);
          break;
        }
        default:
          continue;

      }  // switch

    }  // for of AST

  }  // for of file's reading

}  // end of function
