// TODO:
//  - make  correct adding of output files
//  - do some with if-statemnts to process it correct
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ast.h"
#include "error.h"
#include "file.h"
#include "parser_rules.tab.h"
#include "utilites.h"

#define PINEFAN_VERSION "v0.0.1\n"

int line = 1;
int col = 0;

Vector* program_root = NULL;
extern int yylex(void);
extern FILE* yyin;
char** source_lines = NULL;
int line_count = 0;

void read_source_file(const char* filename) {
  FILE* f = fopen(filename, "r");
  if (!f) return;

  char buffer[1024];
  while (fgets(buffer, sizeof(buffer), f)) {
    source_lines = realloc(source_lines, (line_count + 1) * sizeof(char*));
    source_lines[line_count] = strdup(buffer);
    line_count++;
  }
  fclose(f);
}

void yyerror(const char* s) {
  fprintf(
      stderr,
      "\e[91m[ERROR]\e[0m: %s \e[92mline\e[0m %d \e[94mcoloumn\e[0m %d: %s\n",
      get_file_in(open_in_count - 1)->name, line, col, s);
  char* src = source_lines[line - 1];

  src[strcspn(src, "\n")] = 0;
  fprintf(stderr, "%s\n", src);
  int i = 0;
  for (i = 0; i < col - 1; i++) fputc('~', stderr);
  fprintf(stderr, "\e[1;32m^\e[0m");
  int len = strlen(src);
  int j = col;
  while (j < len) {
    fputc('~', stderr);
    j++;
  }
  fprintf(stderr, "\n");
}

void prologue(struct File* fc, struct File* fs) {
  char* msg =
      "# code generated by the PineFan technology. DO NOT EDIT WITHOUT "
      "NECESSARY\n";

  fwrite(msg, sizeof(char), strlen(msg), fc->f);

  char* info_version = "# - PineFan's version: ";

  fwrite(info_version, sizeof(char), strlen(info_version), fc->f);
  fwrite(PINEFAN_VERSION, sizeof(char), strlen(PINEFAN_VERSION), fc->f);

  char* info_src = "# - source: ";

  fwrite(info_src, sizeof(char), strlen(info_src), fc->f);
  fwrite(fs->name, sizeof(char), strlen(fs->name), fc->f);
  fwrite("\n", sizeof(char), 1, fc->f);
  fwrite("\n", sizeof(char), 1, fc->f);
}

void indicator(char* str, struct File* fc) {
  char* notice = "# indicator\n";
  fwrite(notice, sizeof(char), strlen(notice), fc->f);

  char print[7] = "print(\"";

  fwrite(print, sizeof(print), 1, fc->f);
  fwrite(str, sizeof(char), strlen(str), fc->f);

  char print_end[2] = "\")";

  fwrite(print_end, sizeof(print_end), 1, fc->f);
  fwrite("\n", sizeof(char), 1, fc->f);
}

void strategy(char* str, struct File* fc) {
  char* notice = "# strategy\n";
  fwrite(notice, sizeof(char), strlen(notice), fc->f);

  char print[7] = "print(\"";

  fwrite(print, sizeof(print), 1, fc->f);
  fwrite(str, sizeof(char), strlen(str), fc->f);

  char print_end[2] = "\")";

  fwrite(print_end, sizeof(print_end), 1, fc->f);
  fwrite("\n", sizeof(char), 1, fc->f);
}

void common_var(char* name, ast_node* value, struct File* fc) {
  fwrite(name, sizeof(char), strlen(name), fc->f);
  fwrite(" = ", sizeof(char), 3, fc->f);

  if (value->type == AST_NUMBER) {
    char buf[20] = {0};
    itoa(value->number.value, buf, 10);
    fwrite(buf, sizeof(char), strlen(buf), fc->f);
    fwrite("\n", sizeof(char), 1, fc->f);
    return;
  } else if (value->type == AST_STRING) {
    char brace = '"';
    fwrite(&brace, sizeof(char), 1, fc->f);
    fwrite(value->string.value, sizeof(char), strlen(value->string.value),
           fc->f);
    fwrite(&brace, sizeof(char), 1, fc->f);
    fwrite("\n", sizeof(char), 1, fc->f);
    return;
  }
}

int main(int argc, char* argv[]) {
  file_init();
  program_root = make_vector();

  for (int i = 1; i < argc; i++) {
    bool ok = check_suffix(argv[i]);
    if (!ok) {
      fprintf(stderr, "%s doesn't have the .pine extension\n", argv[i]);
      return 1;
    }

    FILE* fp_for_read = fopen(argv[i], "rb");
    if (!fp_for_read) {
      fprintf(stderr, "error of opening %s\n", argv[i]);
      return 1;
    }

    struct File* f_read = calloc(1, sizeof(struct File));
    f_read->f = fp_for_read;
    f_read->name = argv[i];

    add_input_file(f_read);
  }

  for (int i = 0; i < argc; i++) {
    struct File* curr_file = get_file_in(i);

    yyin = curr_file->f;

    read_source_file(curr_file->name);

    char* py_suffix = replace_suffix(argv[i + 1]);

    FILE* fp_for_write = fopen(py_suffix, "wb");
    if (!fp_for_write) {
      return 1;
    }

    struct File* f_write = calloc(1, sizeof(struct File));
    f_write->f = fp_for_write;
    f_write->name = py_suffix;

    int r = yyparse();

    if (r) exit(1);

    prologue(f_write, curr_file);

    for (int j = 0; j < vec_len(program_root); j++) {
      struct ast_node* val = (struct ast_node*)vec_get(program_root, j);

      switch (val->type) {
        case AST_INDICATOR: {
          indicator(val->string.value, f_write);
          break;
        }
        case AST_STRATEGY: {
          strategy(val->string.value, f_write);
          break;
        }
        case AST_ASSIGN: {
          common_var(val->assign.name, val->assign.value, f_write);
          break;
        }
        default:
          continue;

      }  // switch

    }  // for of AST

  }  // for of file's reading

}  // end of function
