// TODO:
//  - make  correct adding of output files
//  - do some with if-statemnts to process it correct
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <stack>
#include <string>
#include <string_view>
#include <vector>

extern "C" {
#include "ast.h"
#include "parser_rules.tab.h"
#include "vector.h"
}

#include "file.hpp"
#include "ppp.hpp"

#define PINEFAN_VERSION "v0.0.1\n"

int line = 1;
int col = 0;

std::vector<struct ast_node*> program_cpp_root;
Vector* program_root;

void convert_program_root() {
  if (!program_root) return;

  program_cpp_root.clear();
  program_cpp_root.reserve(program_root->len);

  for (int i = 0; i < program_root->len; i++) {
    ast_node* node = static_cast<ast_node*>(program_root->body[i]);
    program_cpp_root.push_back(node);
  }
}

void fast_toupper(char* str) {
  for (int i = 0; str[i]; i++) {
    if (str[i] >= 'a' && str[i] <= 'z') {
      str[i] -= 32;
    }
  }
}

extern int yylex(void);
extern FILE* yyin;
int line_count = 0;
extern int open_in_count;

std::vector<std::string> source_lines;

void read_source_file(const std::filesystem::path& filename) {
  std::ifstream file(filename);
  if (!file.is_open()) return;

  std::string line;
  while (std::getline(file, line)) {
    source_lines.push_back(line);
  }
}

extern "C" {
void yyerror(const char* s) {
  const std::string_view& message(s);

  auto* file = Pinefan::File::preprocessed_files.back();
  if (line > 1) line--;
  std::cerr << std::format(
      "\e[91m[ERROR]\e[0m: {} \e[92mline\e[0m {} \e[94mcolumn\e[0m {}: {}\n",
      file->get_name(), line, col, message);

  if (source_lines.empty() ||
      static_cast<size_t>(line - 1) >= source_lines.size()) {
    return;
  }

  std::string_view src = source_lines[line - 1];
  if (src.ends_with('\n')) {
    src.remove_suffix(1);
  }

  std::cerr << src << '\n';

  if (col > 0) {
    std::cerr << std::string(col - 1, '~') << "\e[1;32m^\e[0m";

    if (static_cast<size_t>(col) <= src.length()) {
      std::cerr << std::string(src.length() - col, '~');
    }
    std::cerr << '\n';
  }
}
}

void prologue(std::ofstream& output, const std::filesystem::path& source_name) {
  output << "# code generated by the PineFan technology. DO NOT EDIT WITHOUT "
            "OF NECESSARY\n"
         << std::format("# - PineFan's version: {}\n", PINEFAN_VERSION)
         << std::format("# - source: {}\n\n", source_name.string());
}

void indicator(std::string_view str, std::ofstream& output) {
  output << std::format("# indicator\nprint(\"{}\")\n", str);
}
void strategy(std::string_view str, std::ofstream& output) {
  output << std::format("# strategy\nprint(\"{}\")\n", str);
}

void common_var(std::string_view name, ast_node* value, std::ofstream& output) {
  if (!value) return;

  switch (value->type) {
    case AST_NUMBER:
      output << std::format("{} = {}\n", name, value->number.value);
      break;

    case AST_STRING:
      output << std::format("{} = \"{}\"\n", name, value->string.value);
      break;

    default:
      // throw "unknown var";
      break;
  }
}

void if_stmt(struct ast_node* cond, struct ast_node* then,
             std::ofstream& output) {
  std::stack<int> indent_stack;

  int start_lev = 2;

  indent_stack.push(start_lev);  // the start level of indentation

  output << std::format("{} ", "if");

  while (cond) {
    // TODO: make generation of condition based on ast kind
    cond++;
  }

  output << std::format("{}\n", ':');

  while (then) {
    then++;

    if (then->type == AST_IF || then->type == AST_WHILE ||
        then->type == AST_FOR)
      indent_stack.push(++start_lev);
    // TODO: make generation based on invokation of other generation functions
  }
}

extern "C" {
void yy_scan_string(const char* str);
void yy_delete_buffer(int);
}

void up_const_names_recursive(ast_node* node, const char* name) {
  if (!node) return;

  switch (node->type) {
    case AST_ASSIGN:
    case AST_CONST:
      if (strcmp(node->assign.name, name) == 0) {
        fast_toupper(node->assign.name);
      }
      up_const_names_recursive(node->assign.value, name);
      break;

    case AST_FOR:
      if (strcmp(node->for_node.var, name) == 0) {
        fast_toupper(node->for_node.var);
      }
      up_const_names_recursive(node->for_node.start, name);
      up_const_names_recursive(node->for_node.end, name);
      up_const_names_recursive(node->for_node.step, name);
      up_const_names_recursive(node->for_node.body, name);
      break;

    case AST_WHILE:
      up_const_names_recursive(node->while_node.cond, name);
      up_const_names_recursive(node->while_node.body, name);
      break;

    case AST_IF:
      up_const_names_recursive(node->if_node.cond, name);
      up_const_names_recursive(node->if_node.then, name);
      up_const_names_recursive(node->if_node.else_, name);
      break;

    case AST_RETURN:
      up_const_names_recursive(node->return_node.value, name);
      break;

    case AST_BINOP:
      up_const_names_recursive(node->binop.left, name);
      up_const_names_recursive(node->binop.right, name);
      break;

    case AST_UNOP:
      up_const_names_recursive(node->unop.operand, name);
      break;

    case AST_CALL:
      for (int i = 0; i < node->call.arg_count; i++) {
        up_const_names_recursive(node->call.args[i], name);
      }
      break;

    case AST_VAR:
    case AST_SIMPLE:
      if (strcmp(node->var.name, name) == 0) {
        fast_toupper(node->var.name);
      }
      break;

    case AST_INDICATOR:
    case AST_STRATEGY:
    case AST_IMPORT:
      // skip string literals (per your request)
      break;

    case AST_NUMBER:
    case AST_STRING:
    default:
      // leaf nodes — nothing to do
      break;
  }
}

void gen_switch_speak(bool is_case,std::ofstream& output,std::string indent_str) {
if(is_case) {
      output << "\n#in source code version that was switch-statement. Since Python doesn't it(but only since 3.10),PineFan\n";
      output << "#translates it to if/elif/else construction. Where if-statement is the first condition like in switch-statement\n";
      output << "#elif is all the other conditions\n"; 
      output << "#and else - it's an optional last condition like default in switch-statement\n\n";

      output << indent_str << "if ";
     return; 
} else {
output << "\n#in source code version that was switch-statement. Since Python doesn't it(but only since 3.10),PineFan\n";
output << "#translates it to if construction\n";
output << "#where if - it's a default-like condition that executes as always\n\n";

output << indent_str << "if ";
return;
}

}

void generate_code(ast_node* node, std::ofstream& output, int indent = 0) {
  if (!node) return;

  std::string indent_str(indent, ' ');
  std::string indent_next(indent + 4, ' ');

  switch (node->type) {
    case AST_IF: {
      output << indent_str << "if ";
      generate_code(node->if_node.cond, output, 0);
      output << ":\n";
      generate_code(node->if_node.then, output, indent + 4);
      if (node->if_node.else_) {
        output << indent_str << "else:\n";
        generate_code(node->if_node.else_, output, indent + 4);
      }
      break;
    }

    case AST_SWITCH: { 
      struct ast_node* first_case = node->switch_node.cases;
      struct ast_node* const_first_case = node->switch_node.expr;
      bool is_only_def = false;

      if(first_case == NULL) {
      gen_switch_speak(false,output,indent_str);
      output << "True:\n";
        generate_code(node->switch_node.default_body->default_stmt.switch_blk_node,
                        output);
	output << "\n";

     is_only_def = true;   
      }

      
      else if(first_case != NULL) {
	gen_switch_speak(true,output,indent_str);
	while (first_case->switch_case.next != NULL) {
        first_case = first_case->switch_case.next;
      }
      
     generate_code(const_first_case,output,0); 
      output << " == ";
      generate_code(first_case->case_stmt.expr, output, 0);

      output << ":\n";
      generate_code(first_case->case_stmt.switch_blk_node, output);

      first_case = node->switch_node.cases;
      
      if(first_case != NULL) {
      while (first_case->switch_case.next != NULL) {
        output << indent_str << "\nelif ";
        generate_code(const_first_case, output, 0);
        output << " == ";
        generate_code(first_case->case_stmt.expr, output, 0);
        output << ":\n";
        generate_code(first_case->case_stmt.switch_blk_node, output);
        first_case = first_case->switch_case.next;
      }
      }
      }
      
      if (node->switch_node.default_body != NULL && !is_only_def) {
        output << "\nelse ";
        output << ":\n";
        
	
        generate_code(node->switch_node.default_body->default_stmt.switch_blk_node,
                        output);
      }
      break;
    }

    case AST_BINOP: {
      output << "(";
      generate_code(node->binop.left, output, 0);
      output << " " << node->binop.op << " ";
      generate_code(node->binop.right, output, 0);
      output << ")";
      break;
    }

    case AST_NUMBER: {
      output << node->number.value;
      break;
    }

    case AST_VAR: {
      output << node->var.name;
      break;
    }

    case AST_STRING: {
      output << "\"" << node->string.value << "\"";
      break;
    }

    case AST_CALL: {
      output << node->call.name << "(";
      for (int i = 0; i < node->call.arg_count; i++) {
        generate_code(node->call.args[i], output, 0);
        if (i + 1 < node->call.arg_count) output << ", ";
      }
      output << ")";
      break;
    }

    case AST_UNOP: {
      output << node->unop.op;
      generate_code(node->unop.operand, output, 0);
      break;
    }

    case AST_RETURN: {
      output << indent_str << "return ";
      generate_code(node->return_node.value, output, 0);
      output << "\n";
      break;
    }

    case AST_ASSIGN: {
      output << indent_str << node->assign.name << " = ";
      generate_code(node->assign.value, output, 0);
      output << "\n";
      break;
    }

    case AST_CONST: {
      output << "#constant variable!" << std::endl;
      up_const_names_recursive(node, node->assign.name);
      output << indent_str << node->assign.name << " = ";
      generate_code(node->assign.value, output, 0);
      output << "\n";
      break;
    }

    case AST_FOR: {
      // PineScript: for var = start to end [by step]
      // Python: for var in range(start, end + 1, step)

      output << indent_str << "for ";
      output << node->for_node.var;  // имя переменной (char*)
      output << " in range(";
      generate_code(node->for_node.start, output, 0);
      output << ", ";
      generate_code(node->for_node.end, output, 0);
      output << " + 1";  // PineScript includes end, Python range excludes end

      if (node->for_node.step) {
        output << ", ";
        generate_code(node->for_node.step, output, 0);
      }

      output << "):\n";
      generate_code(node->for_node.body, output, indent + 4);
      break;
    }
    case AST_WHILE: {
      output << indent_str << "while ";
      generate_code(node->while_node.cond, output, 0);
      output << ":\n";
      generate_code(node->while_node.body, output, indent + 4);
      break;
    }

    case AST_BREAK: {
      output << indent_str << "break\n";
      break;
    }

    case AST_CONTINUE: {
      output << indent_str << "continue\n";
      break;
    }

    case AST_INDICATOR: {
      indicator(node->string.value, output);
      break;
    }

    case AST_STRATEGY: {
      strategy(node->string.value, output);
      break;
    }

    case AST_SWITCH_BLOCK: {
      generate_code(node->switch_block_node.th, output);
      if (node->switch_block_node.prev != NULL) {
        node->switch_block_node.th = node->switch_block_node.prev;
        //generate_code(node->switch_block_node.th, output);
      }
      break;
    }
    default: {
      output << indent_str << "# TODO: unknown node type " << node->type
             << "\n";
      break;
    }
  }
}
int main(int argc, char* argv[]) {
  Pinefan::Ppp::preprocess_files(argc, argv);
  // yydebug = 1;
  for (int i = 0; i < Pinefan::File::preprocessed_files.size(); i++) {
    Pinefan::File::Prp_file* prped_file =
        Pinefan::File::preprocessed_files.at(i);

    yy_scan_string(prped_file->get_content().c_str());

    read_source_file(prped_file->get_name());

    std::string name = prped_file->get_name();

    std::string pure_name(name.begin(), name.end() - 5);

    std::ofstream output_file(pure_name +
                              Pinefan::File::output_exstension.data());

    program_root = make_vector();
    int r = yyparse();

    if (r) exit(1);

    convert_program_root();
    vec_free(program_root);

    prologue(output_file, prped_file->get_name());

    for (int j = 0; j < program_cpp_root.size(); j++) {
      auto* val = program_cpp_root.at(j);
      generate_code(val, output_file);
    }
  }

  ast_free(program_cpp_root.at(0));
  Pinefan::Ppp::clean_prp_files();
}
