#include <fstream>
#include <iostream>

#ifndef _WIN32
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#endif

#ifdef _WIN32
#include <direct.h>
#include <windows.h>
#define mkdir _mkdir
#define chdir _chdir
#endif

#include "color.h"
#include "generate_matrolib.hpp"

int mkmatrolib() {
#ifdef _WIN32
  return mkdir("matrolib");
#else
  return mkdir("matrolib", 0777);
#endif
}

int generate_na() {
  int res = chdir("matrolib");
  std::ofstream output_file("na.py");

  output_file << R"(from typing import TypeAlias, Any

class NA:
    """PineScript-like 'na' value."""

    def __repr__(self):
        return "na"

    def __str__(self):
        return "na"

    # Arithmetic propagates na
    def __add__(self, other):
        return self

    __radd__ = __add__

    def __sub__(self, other):
        return self

    __rsub__ = __sub__

    def __mul__(self, other):
        return self

    __rmul__ = __mul__

    def __truediv__(self, other):
        return self

    __rtruediv__ = __truediv__

    def __pow__(self, other):
        return self

    __rpow__ = __pow__

    # Comparisons always return False
    def __eq__(self, other):
        return False

    def __ne__(self, other):
        return True

    def __lt__(self, other):
        return False

    def __le__(self, other):
        return False

    def __gt__(self, other):
        return False

    def __ge__(self, other):
        return False

    # Cannot be used as a boolean
    def __bool__(self):
        raise TypeError("The truth value of 'na' is undefined. Use is_na().")

def is_na(value):
    return value is na

na = NA()

SeriesValue: TypeAlias = Any | NA
)";

  return res;
}

int generate_ta() {
  int res = chdir("matrolib");
  std::ofstream output_file("ta.py");

  output_file << R"(#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

from .na import na, is_na, SeriesValue


def sma(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.sma(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        # If any value in the window is na,
        # the result for this bar is na.
        if any(is_na(v) for v in window):
            continue

        result[i] = sum(window) / length

    return result

def wma(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.wma(source, length).

    The newest value has the greatest weight.
    For length = 4:
        weights = [1, 2, 3, 4]
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    weight_sum = length * (length + 1) / 2

    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        # Pine propagates na
        if any(is_na(v) for v in window):
            continue

        weighted_sum = 0.0

        for weight, value in enumerate(window, start=1):
            weighted_sum += value * weight

        result[i] = weighted_sum / weight_sum

    return result


def rma(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.rma(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    # Find the first valid SMA
    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        if any(is_na(v) for v in window):
            continue

        first = sum(window) / length
        result[i] = first

        # Continue recursively
        prev = first

        for j in range(i + 1, len(source)):
            if is_na(source[j]):
                result[j] = na
                continue

            prev = (prev * (length - 1) + source[j]) / length
            result[j] = prev

        break

    return result


def cci(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.cci(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    # Reuse our SMA implementation
    sma_values = sma(source, length)

    for i in range(length - 1, len(source)):
        if is_na(sma_values[i]):
            continue

        window = source[i - length + 1 : i + 1]

        # Pine propagates na
        if any(is_na(v) for v in window):
            continue

        mean = sma_values[i]

        # Mean Absolute Deviation (MAD)
        mad = sum(abs(v - mean) for v in window) / length

        # Pine returns na when MAD is zero
        if mad == 0:
            continue

        result[i] = (source[i] - mean) / (0.015 * mad)

    return result

def ema(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.ema(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    alpha = 2 / (length + 1)

    # Seed with SMA
    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        if any(is_na(v) for v in window):
            continue

        prev = sum(window) / length
        result[i] = prev

        for j in range(i + 1, len(source)):
            if is_na(source[j]):
                result[j] = na
                continue

            prev = alpha * source[j] + (1 - alpha) * prev
            result[j] = prev

        break

    return result

def highest(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        result[i] = max(window)

    return result

def lowest(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        result[i] = min(window)

    return result

def stdev(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        mean = sum(window) / length

        variance = sum(
            (v - mean) ** 2
            for v in window
        ) / length

        result[i] = variance ** 0.5

    return result

def change(source: list[SeriesValue]) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(1, len(source)):
        if is_na(source[i]) or is_na(source[i-1]):
            continue

        result[i] = source[i] - source[i-1]

    return result

def rising(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.rising(source, length).

    Returns true if the current value is greater than all previous
    values in the lookback period.
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length, len(source)):
        window = source[i-length:i+1]

        if any(is_na(v) for v in window):
            continue

        current = source[i]

        result[i] = all(
            current > window[j]
            for j in range(length)
        )

    return result

def falling(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.falling(source, length).

    Returns true if the current value is lower than all previous
    values in the lookback period.
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length, len(source)):
        window = source[i-length:i+1]

        if any(is_na(v) for v in window):
            continue

        current = source[i]

        result[i] = all(
            current < window[j]
            for j in range(length)
        )

    return result

def crossover(
    source1: list[SeriesValue],
    source2: list[SeriesValue],
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.crossover(source1, source2).
    """

    if len(source1) != len(source2):
        raise ValueError("source1 and source2 must have the same length")

    result = [na] * len(source1)

    for i in range(1, len(source1)):
        if (
            is_na(source1[i]) or
            is_na(source2[i]) or
            is_na(source1[i-1]) or
            is_na(source2[i-1])
        ):
            continue

        result[i] = (
            source1[i] > source2[i]
            and source1[i-1] <= source2[i-1]
        )

    return result

def crossunder(
    source1: list[SeriesValue],
    source2: list[SeriesValue],
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.crossunder(source1, source2).
    """

    if len(source1) != len(source2):
        raise ValueError("source1 and source2 must have the same length")

    result = [na] * len(source1)

    for i in range(1, len(source1)):
        if (
            is_na(source1[i]) or
            is_na(source2[i]) or
            is_na(source1[i-1]) or
            is_na(source2[i-1])
        ):
            continue

        result[i] = (
            source1[i] < source2[i]
            and source1[i-1] >= source2[i-1]
        )

    return result

def atr(
    high: list[SeriesValue],
    low: list[SeriesValue],
    close: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.atr(length).
    """

    if not (len(high) == len(low) == len(close)):
        raise ValueError("high, low and close must have same length")

    tr = [na] * len(close)

    for i in range(len(close)):
        if (
            is_na(high[i]) or
            is_na(low[i]) or
            is_na(close[i])
        ):
            continue

        if i == 0 or is_na(close[i-1]):
            tr[i] = high[i] - low[i]
        else:
            tr[i] = max(
                high[i] - low[i],
                abs(high[i] - close[i-1]),
                abs(low[i] - close[i-1])
            )

    return rma(tr, length)

def rsi(
    source: list[SeriesValue],
    length: int
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.rsi(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    changes = change(source)

    gains = [na] * len(source)
    losses = [na] * len(source)

    for i, c in enumerate(changes):
        if is_na(c):
            continue

        gains[i] = max(c, 0)
        losses[i] = max(-c, 0)

    avg_gain = rma(gains, length)
    avg_loss = rma(losses, length)

    result = [na] * len(source)

    for i in range(len(source)):
        if is_na(avg_gain[i]) or is_na(avg_loss[i]):
            continue

        if avg_loss[i] == 0:
            result[i] = 100
            continue

        rs = avg_gain[i] / avg_loss[i]

        result[i] = 100 - (100 / (1 + rs))

    return result

def macd(
    source: list[SeriesValue],
    fast_length: int,
    slow_length: int,
    signal_length: int,
):
    """
    PineScript equivalent of ta.macd().
    """

    fast = ema(source, fast_length)
    slow = ema(source, slow_length)

    macd_line = [na] * len(source)

    for i in range(len(source)):
        if is_na(fast[i]) or is_na(slow[i]):
            continue

        macd_line[i] = fast[i] - slow[i]

    signal = ema(macd_line, signal_length)

    histogram = [na] * len(source)

    for i in range(len(source)):
        if is_na(macd_line[i]) or is_na(signal[i]):
            continue

        histogram[i] = macd_line[i] - signal[i]

    return macd_line, signal, histogram

def sum(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        result[i] = builtins.sum(window)

    return result

def barssince(condition: list[SeriesValue]) -> list[SeriesValue]:
    result = [na] * len(condition)

    count = na

    for i, value in enumerate(condition):
        if is_na(value):
            continue

        if value:
            count = 0
        elif not is_na(count):
            count += 1

        result[i] = count

    return result

def mom(source, length):
    result = [na] * len(source)

    for i in range(length, len(source)):
        if is_na(source[i]) or is_na(source[i-length]):
            continue

        result[i] = source[i] - source[i-length]

    return result

def roc(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.roc(source, length).

    Rate of Change:
        ((source - source[length]) / source[length]) * 100
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length, len(source)):
        current = source[i]
        previous = source[i - length]

        if is_na(current) or is_na(previous):
            continue

        # Avoid division by zero
        if previous == 0:
            continue

        result[i] = ((current - previous) / previous) * 100

    return result

def bb(
    source: list[SeriesValue],
    length: int,
    mult: float,
) -> tuple[
    list[SeriesValue],
    list[SeriesValue],
    list[SeriesValue],
]:
    """
    PineScript equivalent of ta.bb(source, length, mult).

    Returns:
        (basis, upper, lower)
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    basis = sma(source, length)
    deviation = stdev(source, length)

    upper = [na] * len(source)
    lower = [na] * len(source)

    for i in range(len(source)):
        if is_na(basis[i]) or is_na(deviation[i]):
            continue

        dev = deviation[i] * mult

        upper[i] = basis[i] + dev
        lower[i] = basis[i] - dev

    return basis, upper, lower

def bbw(
    source: list[SeriesValue],
    length: int,
    mult: float,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.bbw(source, length, mult).

    Bollinger Band Width:
        ((upper - lower) / basis)

    where:
        basis = sma(source, length)
        upper = basis + stdev(source, length) * mult
        lower = basis - stdev(source, length) * mult
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    basis = sma(source, length)
    deviation = stdev(source, length)

    result = [na] * len(source)

    for i in range(len(source)):
        if is_na(basis[i]) or is_na(deviation[i]):
            continue

        # Pine returns na if division is impossible
        if basis[i] == 0:
            continue

        result[i] = (
            (2 * deviation[i] * mult)
            / basis[i]
        )

    return result
def barssince(
    condition: list[SeriesValue],
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.barssince(condition).

    Returns the number of bars since the last true condition.
    """

    result = [na] * len(condition)

    count = na

    for i, value in enumerate(condition):
        if is_na(value):
            continue

        if value:
            count = 0
        elif not is_na(count):
            count += 1

        result[i] = count

    return result

def valuewhen(
    condition: list[SeriesValue],
    source: list[SeriesValue],
    occurrence: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.valuewhen(condition, source, occurrence).

    Returns the value of source at the nth most recent true condition.
    """

    if len(condition) != len(source):
        raise ValueError("condition and source must have the same length")

    if occurrence < 0:
        raise ValueError("occurrence must be >= 0")

    result = [na] * len(source)

    history = []

    for i in range(len(source)):
        if is_na(condition[i]):
            continue

        if condition[i]:
            if not is_na(source[i]):
                history.insert(0, source[i])

        if len(history) > occurrence:
            result[i] = history[occurrence]

    return result

def variance(
    source: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.variance(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        mean = sum(window) / length

        result[i] = sum(
            (v - mean) ** 2
            for v in window
        ) / length

    return result

def median(
    source: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.median(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        values = sorted(window)

        middle = length // 2

        if length % 2 == 1:
            # Odd length: return middle element
            result[i] = values[middle]
        else:
            # Even length: average two middle elements
            result[i] = (
                values[middle - 1] +
                values[middle]
            ) / 2

    return result

def linreg(
    source: list[SeriesValue],
    length: int,
    offset: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.linreg(source, length, offset).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    # Precompute x statistics
    x_values = list(range(length))

    x_mean = sum(x_values) / length

    x_variance = sum(
        (x - x_mean) ** 2
        for x in x_values
    )

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        y_mean = sum(window) / length

        covariance = sum(
            (x_values[j] - x_mean) *
            (window[j] - y_mean)
            for j in range(length)
        )

        slope = covariance / x_variance

        intercept = y_mean - slope * x_mean

        result[i] = (
            slope * (length - 1 - offset)
            + intercept
        )

    return result
)";

  return res;
}

int generate_math() {
  int res = chdir("matrolib");
  std::ofstream output_file("math.py");

  output_file << R"(#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

import builtins
import _math

from .na import na, is_na, SeriesValue


def abs(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.abs().
    """

    if is_na(value):
        return na

    return __builtins__["abs"](value)

def max(*values: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.max().
    """

    if any(is_na(v) for v in values):
        return na

    return builtins.max(values)

def min(*values: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.min().
    """

    if any(is_na(v) for v in values):
        return na

    return builtins.min(values)

def sqrt(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.sqrt().
    """

    if is_na(value):
        return na

    if value < 0:
        return na

    return _math.sqrt(value)

def pow(
    base: SeriesValue,
    exponent: SeriesValue,
) -> SeriesValue:
    """
    PineScript equivalent of math.pow().
    """

    if is_na(base) or is_na(exponent):
        return na

    try:
        return _math.pow(base, exponent)
    except (ValueError, OverflowError):
        return na

def floor(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.floor().
    """

    if is_na(value):
        return na

    return _math.floor(value)

def ceil(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.ceil().
    """

    if is_na(value):
        return na

    return _math.ceil(value)

def round(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.round().

    Rounds half values away from zero.
    """

    if is_na(value):
        return na

    if value >= 0:
        return _math.floor(value + 0.5)

    return _math.ceil(value - 0.5)

def acos(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.acos().

    Returns arccosine in radians.
    """

    if is_na(value):
        return na

    if value < -1 or value > 1:
        return na

    return _math.acos(value)

def asin(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.asin().
    """

    if is_na(value):
        return na

    if value < -1 or value > 1:
        return na

    return _math.asin(value)

def atan(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.atan().
    Returns the arctangent in radians.
    """

    if is_na(value):
        return na

    return _math.atan(value)

def avg(*values: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.avg().
    """

    if any(is_na(v) for v in values):
        return na

    if len(values) == 0:
        return na

    return sum(values) / len(values)

def cos(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.cos().

    Input angle is in radians.
    """

    if is_na(value):
        return na

    return _math.cos(value)

    """
    PineScript equivalent of math.exp().
    """

    if is_na(value):
        return na

    try:
        return _math.exp(value)
    except OverflowError:
        return na

def log(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.log().

    Returns natural logarithm (base e).
    """

    if is_na(value):
        return na

    if value <= 0:
        return na

    return _math.log(value)

def log10(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.log10().
    """

    if is_na(value):
        return na

    if value <= 0:
        return na

    return _math.log10(value)

def random(
    min_value: SeriesValue = 0.0,
    max_value: SeriesValue = 1.0,
) -> SeriesValue:
    """
    PineScript equivalent of math.random().

    Returns a random float between min_value and max_value.
    """

    if is_na(min_value) or is_na(max_value):
        return na

    if min_value > max_value:
        return na

    return _random.uniform(min_value, max_value)

def round_to_mintick(
    value: SeriesValue,
    mintick: float,
) -> SeriesValue:
    """
    PineScript equivalent of math.round_to_mintick().

    Rounds value to the nearest valid price tick.
    """

    if is_na(value):
        return na

    if mintick <= 0:
        raise ValueError("mintick must be greater than 0")

    ticks = value / mintick

    # Pine rounds halves away from zero
    if ticks >= 0:
        rounded_ticks = int(ticks + 0.5)
    else:
        rounded_ticks = int(ticks - 0.5)

    return rounded_ticks * mintick

def sign(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.sign().
    
    Returns:
        1  if value > 0
        0  if value == 0
        -1 if value < 0
    """

    if is_na(value):
        return na

    if value > 0:
        return 1

    if value < 0:
        return -1

    return 0

def sum(
    source: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of math.sum(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        if any(is_na(v) for v in window):
            continue

        result[i] = builtins.sum(window)

    return result


def tan(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.tan().

    Input angle is in radians.
    """

    if is_na(value):
        return na

    return _math.tan(value)

def todegrees(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.todegrees().

    Converts radians to degrees.
    """

    if is_na(value):
        return na

    return _math.degrees(value)

def toradians(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.toradians().

    Converts degrees to radians.
    """

    if is_na(value):
        return na

    return _math.radians(value)

)";

  return res;
}

int generate_array() {
  int res = chdir("matrolib");
  std::ofstream output_file("array.py");

  output_file << R"(#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

from .na import na, is_na, SeriesValue


class Array:
    """
    Generic Pine array implementation.
    """

    def __init__(self, size: int = 0, initial=None):
        self._data = [initial] * size

    def __repr__(self):
        return repr(self._data)

    def __len__(self):
        return len(self._data)

    def __getitem__(self, index):
        return self._data[index]

    def __setitem__(self, index, value):
        self._data[index] = value

    def clear(self):
        self._data.clear()

    def copy(self):
        a = Array()
        a._data = self._data.copy()
        return a

    def size(self):
        return len(self._data)

    def push(self, value):
        self._data.append(value)

    def pop(self):
        return self._data.pop()

    def shift(self):
        return self._data.pop(0)

    def unshift(self, value):
        self._data.insert(0, value)

    def insert(self, index, value):
        self._data.insert(index, value)

    def remove(self, index):
        return self._data.pop(index)

    def get(self, index):
        return self._data[index]

    def set(self, index, value):
        self._data[index] = value

    def first(self):
        return self._data[0]

    def last(self):
        return self._data[-1]

    def fill(self, value):
        for i in range(len(self._data)):
            self._data[i] = value

    def reverse(self):
        self._data.reverse()

    def sort(self):
        self._data.sort()

    def includes(self, value):
        return value in self._data

    def indexof(self, value):
        try:
            return self._data.index(value)
        except ValueError:
            return -1

    def lastindexof(self, value):
        for i in range(len(self._data) - 1, -1, -1):
            if self._data[i] == value:
                return i
        return -1

    def join(self, separator=""):
        return separator.join(map(str, self._data))

    def concat(self, other):
        a = self.copy()
        a._data.extend(other._data)
        return a

    def slice(self, begin, end=None):
        a = Array()
        a._data = self._data[begin:end]
        return a

class FloatArray(Array):
    pass


class IntArray(Array):
    pass


class BoolArray(Array):
    pass


class StringArray(Array):
    pass


class ColorArray(Array):
    pass


class LineArray(Array):
    pass


class LabelArray(Array):
    pass


class BoxArray(Array):
    pass


class TableArray(Array):
    pass

class LineFillArray(Array):
    pass


class PolylineArray(Array):
    pass


class ChartPointArray(Array):
    pass


def new_float(size=0, initial=na):
    a = FloatArray()
    a.fill(initial, size)
    return a


def new_int(size=0, initial=na):
    a = IntArray()
    a.fill(initial, size)
    return a


def new_bool(size=0, initial=na):
    a = BoolArray()
    a.fill(initial, size)
    return a


def new_string(size=0, initial=na):
    a = StringArray()
    a.fill(initial, size)
    return a


def new_color(size=0, initial=na):
    a = ColorArray()
    a.fill(initial, size)
    return a
)";

  return res;
}

int generate_color() {
  int res = chdir("matrolib");
  std::ofstream output_file("color.py");

  output_file << R"(#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

from dataclasses import dataclass

from .na import na, is_na, SeriesValue


@dataclass(frozen=True)
class Color:
    r: int
    g: int
    b: int
    t: int = 0      # transparency: 0-100

    def __post_init__(self):
        object.__setattr__(self, "r", max(0, min(255, self.r)))
        object.__setattr__(self, "g", max(0, min(255, self.g)))
        object.__setattr__(self, "b", max(0, min(255, self.b)))
        object.__setattr__(self, "t", max(0, min(100, self.t)))


def rgb(r: int, g: int, b: int, transp: int = 0):
    return Color(r, g, b, transp)

def new(color: Color | SeriesValue, transp: int):
    if is_na(color):
        return na

    return Color(color.r, color.g, color.b, transp)

def r(color):
    if is_na(color):
        return na

    return color.r


def g(color):
    if is_na(color):
        return na

    return color.g

def b(color):
    if is_na(color):
        return na
    return color.b


def t(color):
    if is_na(color):
        return na

    return color.t

black   = Color(0,0,0)
white   = Color(255,255,255)

red     = Color(255,0,0)
green   = Color(0,128,0)
blue    = Color(0,0,255)

yellow  = Color(255,255,0)
orange  = Color(255,165,0)
purple  = Color(128,0,128)

gray    = Color(128,128,128)
silver  = Color(192,192,192)

lime    = Color(0,255,0)
maroon  = Color(128,0,0)
navy    = Color(0,0,128)
olive   = Color(128,128,0)
teal    = Color(0,128,128)
fuchsia = Color(255,0,255)
aqua    = Color(0,255,255)
)";

  return res;
}

int generate_init() {
  int res = chdir("matrolib");
  std::ofstream output_file("__init__.py");
  output_file << R"(# matrolib/__init__.py

from .na import NA, na, is_na
)";

  return res;
}

void generate_matrolib() {
  int res = mkmatrolib();

  if (res != 0) {
#ifdef _WIN32

    YELLOW_COLOR;
    std::cout << "(WARNING): ";
    RESET_COLOR;
    std::cout << "The matrolib folder already exists" << std::endl;
    return;

#else

    std::cout << YELLOW_COLOR << "(WARNING): " << RESET_COLOR
              << "The matrolib folder already exists" << std::endl;
    return;

#endif
  }

  res = 0;
  res = generate_na();
  generate_ta();
  generate_math();
  generate_array();
  generate_color();
  generate_init();

  goto check_err;

check_err:
  if (res != 0) {
#ifdef _WIN32

    YELLOW_COLOR;
    std::cout << "(WARNING): ";
    RESET_COLOR;
    std::cout << "The matrolib folder does not exist" << std::endl;
    return;

#else

    std::cout << YELLOW_COLOR << "(WARNING): " << RESET_COLOR
              << "The matrolib folder does not exist" << std::endl;
    return;

#endif
  }
}
