switch foo
   fff



   fff
if x
      fo
      ral
      rr

foo() => 
     fff
     fff
     
     
     fff




ddd

type ffoo 
   ffo
   ffo


iniddd
didid

dkkdkdkd

dldkdkd


switch fff
   ffff
   fff
   fff
   fff
   if if tototo


switch close[1] > 5
	array<box> real future("hello,it's an ospium,this text is       





	just a stub to test if PPP can parse this hard expr");








funck() => 
   fkfkfkkfkfkfkfkfkfkfkfk























   fffff
