#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

from .na import na, is_na, SeriesValue


class Array:
    """
    Generic Pine array implementation.
    """

    def __init__(self, size: int = 0, initial=None):
        self._data = [initial] * size

    def __repr__(self):
        return repr(self._data)

    def __len__(self):
        return len(self._data)

    def __getitem__(self, index):
        return self._data[index]

    def __setitem__(self, index, value):
        self._data[index] = value

    def clear(self):
        self._data.clear()

    def copy(self):
        a = Array()
        a._data = self._data.copy()
        return a

    def size(self):
        return len(self._data)

    def push(self, value):
        self._data.append(value)

    def pop(self):
        return self._data.pop()

    def shift(self):
        return self._data.pop(0)

    def unshift(self, value):
        self._data.insert(0, value)

    def insert(self, index, value):
        self._data.insert(index, value)

    def remove(self, index):
        return self._data.pop(index)

    def get(self, index):
        return self._data[index]

    def set(self, index, value):
        self._data[index] = value

    def first(self):
        return self._data[0]

    def last(self):
        return self._data[-1]

    def fill(self, value):
        for i in range(len(self._data)):
            self._data[i] = value

    def reverse(self):
        self._data.reverse()

    def sort(self):
        self._data.sort()

    def includes(self, value):
        return value in self._data

    def indexof(self, value):
        try:
            return self._data.index(value)
        except ValueError:
            return -1

    def lastindexof(self, value):
        for i in range(len(self._data) - 1, -1, -1):
            if self._data[i] == value:
                return i
        return -1

    def join(self, separator=""):
        return separator.join(map(str, self._data))

    def concat(self, other):
        a = self.copy()
        a._data.extend(other._data)
        return a

    def slice(self, begin, end=None):
        a = Array()
        a._data = self._data[begin:end]
        return a

class FloatArray(Array):
    pass


class IntArray(Array):
    pass


class BoolArray(Array):
    pass


class StringArray(Array):
    pass


class ColorArray(Array):
    pass


class LineArray(Array):
    pass


class LabelArray(Array):
    pass


class BoxArray(Array):
    pass


class TableArray(Array):
    pass

class LineFillArray(Array):
    pass


class PolylineArray(Array):
    pass


class ChartPointArray(Array):
    pass


def new_float(size=0, initial=na):
    a = FloatArray()
    a.fill(initial, size)
    return a


def new_int(size=0, initial=na):
    a = IntArray()
    a.fill(initial, size)
    return a


def new_bool(size=0, initial=na):
    a = BoolArray()
    a.fill(initial, size)
    return a


def new_string(size=0, initial=na):
    a = StringArray()
    a.fill(initial, size)
    return a


def new_color(size=0, initial=na):
    a = ColorArray()
    a.fill(initial, size)
    return a
