#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

from dataclasses import dataclass

from .na import na, is_na, SeriesValue


@dataclass(frozen=True)
class Color:
    r: int
    g: int
    b: int
    t: int = 0      # transparency: 0-100

    def __post_init__(self):
        object.__setattr__(self, "r", max(0, min(255, self.r)))
        object.__setattr__(self, "g", max(0, min(255, self.g)))
        object.__setattr__(self, "b", max(0, min(255, self.b)))
        object.__setattr__(self, "t", max(0, min(100, self.t)))


def rgb(r: int, g: int, b: int, transp: int = 0):
    return Color(r, g, b, transp)

def new(color: Color | SeriesValue, transp: int):
    if is_na(color):
        return na

    return Color(color.r, color.g, color.b, transp)

def r(color):
    if is_na(color):
        return na

    return color.r


def g(color):
    if is_na(color):
        return na

    return color.g

def b(color):
    if is_na(color):
        return na
    return color.b


def t(color):
    if is_na(color):
        return na

    return color.t

black   = Color(0,0,0)
white   = Color(255,255,255)

red     = Color(255,0,0)
green   = Color(0,128,0)
blue    = Color(0,0,255)

yellow  = Color(255,255,0)
orange  = Color(255,165,0)
purple  = Color(128,0,128)

gray    = Color(128,128,128)
silver  = Color(192,192,192)

lime    = Color(0,255,0)
maroon  = Color(128,0,0)
navy    = Color(0,0,128)
olive   = Color(128,128,0)
teal    = Color(0,128,128)
fuchsia = Color(255,0,255)
aqua    = Color(0,255,255)
