#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

import builtins
import _math

from .na import na, is_na, SeriesValue


def abs(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.abs().
    """

    if is_na(value):
        return na

    return __builtins__["abs"](value)

def max(*values: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.max().
    """

    if any(is_na(v) for v in values):
        return na

    return builtins.max(values)

def min(*values: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.min().
    """

    if any(is_na(v) for v in values):
        return na

    return builtins.min(values)

def sqrt(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.sqrt().
    """

    if is_na(value):
        return na

    if value < 0:
        return na

    return _math.sqrt(value)

def pow(
    base: SeriesValue,
    exponent: SeriesValue,
) -> SeriesValue:
    """
    PineScript equivalent of math.pow().
    """

    if is_na(base) or is_na(exponent):
        return na

    try:
        return _math.pow(base, exponent)
    except (ValueError, OverflowError):
        return na

def floor(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.floor().
    """

    if is_na(value):
        return na

    return _math.floor(value)

def ceil(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.ceil().
    """

    if is_na(value):
        return na

    return _math.ceil(value)

def round(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.round().

    Rounds half values away from zero.
    """

    if is_na(value):
        return na

    if value >= 0:
        return _math.floor(value + 0.5)

    return _math.ceil(value - 0.5)

def acos(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.acos().

    Returns arccosine in radians.
    """

    if is_na(value):
        return na

    if value < -1 or value > 1:
        return na

    return _math.acos(value)

def asin(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.asin().
    """

    if is_na(value):
        return na

    if value < -1 or value > 1:
        return na

    return _math.asin(value)

def atan(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.atan().
    Returns the arctangent in radians.
    """

    if is_na(value):
        return na

    return _math.atan(value)

def avg(*values: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.avg().
    """

    if any(is_na(v) for v in values):
        return na

    if len(values) == 0:
        return na

    return sum(values) / len(values)

def cos(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.cos().

    Input angle is in radians.
    """

    if is_na(value):
        return na

    return _math.cos(value)

    """
    PineScript equivalent of math.exp().
    """

    if is_na(value):
        return na

    try:
        return _math.exp(value)
    except OverflowError:
        return na

def log(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.log().

    Returns natural logarithm (base e).
    """

    if is_na(value):
        return na

    if value <= 0:
        return na

    return _math.log(value)

def log10(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.log10().
    """

    if is_na(value):
        return na

    if value <= 0:
        return na

    return _math.log10(value)

def random(
    min_value: SeriesValue = 0.0,
    max_value: SeriesValue = 1.0,
) -> SeriesValue:
    """
    PineScript equivalent of math.random().

    Returns a random float between min_value and max_value.
    """

    if is_na(min_value) or is_na(max_value):
        return na

    if min_value > max_value:
        return na

    return _random.uniform(min_value, max_value)

def round_to_mintick(
    value: SeriesValue,
    mintick: float,
) -> SeriesValue:
    """
    PineScript equivalent of math.round_to_mintick().

    Rounds value to the nearest valid price tick.
    """

    if is_na(value):
        return na

    if mintick <= 0:
        raise ValueError("mintick must be greater than 0")

    ticks = value / mintick

    # Pine rounds halves away from zero
    if ticks >= 0:
        rounded_ticks = int(ticks + 0.5)
    else:
        rounded_ticks = int(ticks - 0.5)

    return rounded_ticks * mintick

def sign(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.sign().
    
    Returns:
        1  if value > 0
        0  if value == 0
        -1 if value < 0
    """

    if is_na(value):
        return na

    if value > 0:
        return 1

    if value < 0:
        return -1

    return 0

def sum(
    source: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of math.sum(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        if any(is_na(v) for v in window):
            continue

        result[i] = builtins.sum(window)

    return result


def tan(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.tan().

    Input angle is in radians.
    """

    if is_na(value):
        return na

    return _math.tan(value)

def todegrees(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.todegrees().

    Converts radians to degrees.
    """

    if is_na(value):
        return na

    return _math.degrees(value)

def toradians(value: SeriesValue) -> SeriesValue:
    """
    PineScript equivalent of math.toradians().

    Converts degrees to radians.
    """

    if is_na(value):
        return na

    return _math.radians(value)

