#This is a PineScript runtime library
#generated by the PineFan technology. DO NOT EDIT WITHOUT OF NECCESSARY

from .na import na, is_na, SeriesValue


def sma(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.sma(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        # If any value in the window is na,
        # the result for this bar is na.
        if any(is_na(v) for v in window):
            continue

        result[i] = sum(window) / length

    return result

def wma(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.wma(source, length).

    The newest value has the greatest weight.
    For length = 4:
        weights = [1, 2, 3, 4]
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    weight_sum = length * (length + 1) / 2

    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        # Pine propagates na
        if any(is_na(v) for v in window):
            continue

        weighted_sum = 0.0

        for weight, value in enumerate(window, start=1):
            weighted_sum += value * weight

        result[i] = weighted_sum / weight_sum

    return result


def rma(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.rma(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    # Find the first valid SMA
    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        if any(is_na(v) for v in window):
            continue

        first = sum(window) / length
        result[i] = first

        # Continue recursively
        prev = first

        for j in range(i + 1, len(source)):
            if is_na(source[j]):
                result[j] = na
                continue

            prev = (prev * (length - 1) + source[j]) / length
            result[j] = prev

        break

    return result


def cci(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.cci(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    # Reuse our SMA implementation
    sma_values = sma(source, length)

    for i in range(length - 1, len(source)):
        if is_na(sma_values[i]):
            continue

        window = source[i - length + 1 : i + 1]

        # Pine propagates na
        if any(is_na(v) for v in window):
            continue

        mean = sma_values[i]

        # Mean Absolute Deviation (MAD)
        mad = sum(abs(v - mean) for v in window) / length

        # Pine returns na when MAD is zero
        if mad == 0:
            continue

        result[i] = (source[i] - mean) / (0.015 * mad)

    return result

def ema(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.ema(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    alpha = 2 / (length + 1)

    # Seed with SMA
    for i in range(length - 1, len(source)):
        window = source[i - length + 1 : i + 1]

        if any(is_na(v) for v in window):
            continue

        prev = sum(window) / length
        result[i] = prev

        for j in range(i + 1, len(source)):
            if is_na(source[j]):
                result[j] = na
                continue

            prev = alpha * source[j] + (1 - alpha) * prev
            result[j] = prev

        break

    return result

def highest(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        result[i] = max(window)

    return result

def lowest(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        result[i] = min(window)

    return result

def stdev(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        mean = sum(window) / length

        variance = sum(
            (v - mean) ** 2
            for v in window
        ) / length

        result[i] = variance ** 0.5

    return result

def change(source: list[SeriesValue]) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(1, len(source)):
        if is_na(source[i]) or is_na(source[i-1]):
            continue

        result[i] = source[i] - source[i-1]

    return result

def rising(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.rising(source, length).

    Returns true if the current value is greater than all previous
    values in the lookback period.
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length, len(source)):
        window = source[i-length:i+1]

        if any(is_na(v) for v in window):
            continue

        current = source[i]

        result[i] = all(
            current > window[j]
            for j in range(length)
        )

    return result

def falling(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.falling(source, length).

    Returns true if the current value is lower than all previous
    values in the lookback period.
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length, len(source)):
        window = source[i-length:i+1]

        if any(is_na(v) for v in window):
            continue

        current = source[i]

        result[i] = all(
            current < window[j]
            for j in range(length)
        )

    return result

def crossover(
    source1: list[SeriesValue],
    source2: list[SeriesValue],
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.crossover(source1, source2).
    """

    if len(source1) != len(source2):
        raise ValueError("source1 and source2 must have the same length")

    result = [na] * len(source1)

    for i in range(1, len(source1)):
        if (
            is_na(source1[i]) or
            is_na(source2[i]) or
            is_na(source1[i-1]) or
            is_na(source2[i-1])
        ):
            continue

        result[i] = (
            source1[i] > source2[i]
            and source1[i-1] <= source2[i-1]
        )

    return result

def crossunder(
    source1: list[SeriesValue],
    source2: list[SeriesValue],
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.crossunder(source1, source2).
    """

    if len(source1) != len(source2):
        raise ValueError("source1 and source2 must have the same length")

    result = [na] * len(source1)

    for i in range(1, len(source1)):
        if (
            is_na(source1[i]) or
            is_na(source2[i]) or
            is_na(source1[i-1]) or
            is_na(source2[i-1])
        ):
            continue

        result[i] = (
            source1[i] < source2[i]
            and source1[i-1] >= source2[i-1]
        )

    return result

def atr(
    high: list[SeriesValue],
    low: list[SeriesValue],
    close: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.atr(length).
    """

    if not (len(high) == len(low) == len(close)):
        raise ValueError("high, low and close must have same length")

    tr = [na] * len(close)

    for i in range(len(close)):
        if (
            is_na(high[i]) or
            is_na(low[i]) or
            is_na(close[i])
        ):
            continue

        if i == 0 or is_na(close[i-1]):
            tr[i] = high[i] - low[i]
        else:
            tr[i] = max(
                high[i] - low[i],
                abs(high[i] - close[i-1]),
                abs(low[i] - close[i-1])
            )

    return rma(tr, length)

def rsi(
    source: list[SeriesValue],
    length: int
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.rsi(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    changes = change(source)

    gains = [na] * len(source)
    losses = [na] * len(source)

    for i, c in enumerate(changes):
        if is_na(c):
            continue

        gains[i] = max(c, 0)
        losses[i] = max(-c, 0)

    avg_gain = rma(gains, length)
    avg_loss = rma(losses, length)

    result = [na] * len(source)

    for i in range(len(source)):
        if is_na(avg_gain[i]) or is_na(avg_loss[i]):
            continue

        if avg_loss[i] == 0:
            result[i] = 100
            continue

        rs = avg_gain[i] / avg_loss[i]

        result[i] = 100 - (100 / (1 + rs))

    return result

def macd(
    source: list[SeriesValue],
    fast_length: int,
    slow_length: int,
    signal_length: int,
):
    """
    PineScript equivalent of ta.macd().
    """

    fast = ema(source, fast_length)
    slow = ema(source, slow_length)

    macd_line = [na] * len(source)

    for i in range(len(source)):
        if is_na(fast[i]) or is_na(slow[i]):
            continue

        macd_line[i] = fast[i] - slow[i]

    signal = ema(macd_line, signal_length)

    histogram = [na] * len(source)

    for i in range(len(source)):
        if is_na(macd_line[i]) or is_na(signal[i]):
            continue

        histogram[i] = macd_line[i] - signal[i]

    return macd_line, signal, histogram

def sum(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        result[i] = builtins.sum(window)

    return result

def barssince(condition: list[SeriesValue]) -> list[SeriesValue]:
    result = [na] * len(condition)

    count = na

    for i, value in enumerate(condition):
        if is_na(value):
            continue

        if value:
            count = 0
        elif not is_na(count):
            count += 1

        result[i] = count

    return result

def mom(source, length):
    result = [na] * len(source)

    for i in range(length, len(source)):
        if is_na(source[i]) or is_na(source[i-length]):
            continue

        result[i] = source[i] - source[i-length]

    return result

def roc(source: list[SeriesValue], length: int) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.roc(source, length).

    Rate of Change:
        ((source - source[length]) / source[length]) * 100
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length, len(source)):
        current = source[i]
        previous = source[i - length]

        if is_na(current) or is_na(previous):
            continue

        # Avoid division by zero
        if previous == 0:
            continue

        result[i] = ((current - previous) / previous) * 100

    return result

def bb(
    source: list[SeriesValue],
    length: int,
    mult: float,
) -> tuple[
    list[SeriesValue],
    list[SeriesValue],
    list[SeriesValue],
]:
    """
    PineScript equivalent of ta.bb(source, length, mult).

    Returns:
        (basis, upper, lower)
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    basis = sma(source, length)
    deviation = stdev(source, length)

    upper = [na] * len(source)
    lower = [na] * len(source)

    for i in range(len(source)):
        if is_na(basis[i]) or is_na(deviation[i]):
            continue

        dev = deviation[i] * mult

        upper[i] = basis[i] + dev
        lower[i] = basis[i] - dev

    return basis, upper, lower

def bbw(
    source: list[SeriesValue],
    length: int,
    mult: float,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.bbw(source, length, mult).

    Bollinger Band Width:
        ((upper - lower) / basis)

    where:
        basis = sma(source, length)
        upper = basis + stdev(source, length) * mult
        lower = basis - stdev(source, length) * mult
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    basis = sma(source, length)
    deviation = stdev(source, length)

    result = [na] * len(source)

    for i in range(len(source)):
        if is_na(basis[i]) or is_na(deviation[i]):
            continue

        # Pine returns na if division is impossible
        if basis[i] == 0:
            continue

        result[i] = (
            (2 * deviation[i] * mult)
            / basis[i]
        )

    return result
def barssince(
    condition: list[SeriesValue],
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.barssince(condition).

    Returns the number of bars since the last true condition.
    """

    result = [na] * len(condition)

    count = na

    for i, value in enumerate(condition):
        if is_na(value):
            continue

        if value:
            count = 0
        elif not is_na(count):
            count += 1

        result[i] = count

    return result

def valuewhen(
    condition: list[SeriesValue],
    source: list[SeriesValue],
    occurrence: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.valuewhen(condition, source, occurrence).

    Returns the value of source at the nth most recent true condition.
    """

    if len(condition) != len(source):
        raise ValueError("condition and source must have the same length")

    if occurrence < 0:
        raise ValueError("occurrence must be >= 0")

    result = [na] * len(source)

    history = []

    for i in range(len(source)):
        if is_na(condition[i]):
            continue

        if condition[i]:
            if not is_na(source[i]):
                history.insert(0, source[i])

        if len(history) > occurrence:
            result[i] = history[occurrence]

    return result

def variance(
    source: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.variance(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        mean = sum(window) / length

        result[i] = sum(
            (v - mean) ** 2
            for v in window
        ) / length

    return result

def median(
    source: list[SeriesValue],
    length: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.median(source, length).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        values = sorted(window)

        middle = length // 2

        if length % 2 == 1:
            # Odd length: return middle element
            result[i] = values[middle]
        else:
            # Even length: average two middle elements
            result[i] = (
                values[middle - 1] +
                values[middle]
            ) / 2

    return result

def linreg(
    source: list[SeriesValue],
    length: int,
    offset: int,
) -> list[SeriesValue]:
    """
    PineScript equivalent of ta.linreg(source, length, offset).
    """

    if length <= 0:
        raise ValueError("length must be greater than 0")

    result = [na] * len(source)

    # Precompute x statistics
    x_values = list(range(length))

    x_mean = sum(x_values) / length

    x_variance = sum(
        (x - x_mean) ** 2
        for x in x_values
    )

    for i in range(length - 1, len(source)):
        window = source[i-length+1:i+1]

        if any(is_na(v) for v in window):
            continue

        y_mean = sum(window) / length

        covariance = sum(
            (x_values[j] - x_mean) *
            (window[j] - y_mean)
            for j in range(length)
        )

        slope = covariance / x_variance

        intercept = y_mean - slope * x_mean

        result[i] = (
            slope * (length - 1 - offset)
            + intercept
        )

    return result
